### ISSUE TITLE
Changing the Bot's Status

### ISSUE THREAD

**Issue by oppars01** [KillStr3aK/discord-api#4]
The bot seems to be offline all the time. Can an api be written for this? Making bot status like "online","idle" etc. Also, if this can be done, change places such as the playing part. I looked a bit, but I couldn't find an api for it.

**Comment by KillStr3aK** [comment]
This library is limited to the [basic REST API](https://discord.com/developers/docs/intro) that Discord provides, everything that is under "Resources" will be supported but to change the bot status it would require an active WSS (WebSocket Secure) connection to the discord gateways, and there is no extension in SourcePawn yet to do that, at least there wasn't in the past not sure about now.

If you go through the code you can see that I've already made some progress towards the gateway things like intents, bot activities and so on, but everything that would make the bot 'alive' is done through wss.

I got a workaround in my mind but haven't tested yet at all.
